version: '3'

services:
  abibliadigital:
    build: ./docker-api
    command: [ "bash", "/usr/src/api/start.sh" ]
    environment:
      - MONGODB_URI=mongodb://abibliadigital-mongo/abibliadigital
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://abibliadigital-redis
    volumes:
      - abibliadigital:/usr/src/api
    depends_on:
      - abibliadigital-mongo
      - abibliadigital-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.biblia-api.rule=Host(`biblia-api.vitordaniel.com`)"
      - "traefik.http.routers.biblia-api.entrypoints=websecure"
      - "traefik.http.services.biblia-api.loadbalancer.server.port=3000"

  abibliadigital-mongo:
    build: ./docker-mongo
    volumes:
      - mongo-abibliadigital-db-data:/data/db
      - mongo-abibliadigital-db-log:/var/log/mongodb

  abibliadigital-redis:
    image: "redis:alpine"
    command: redis-server
    restart: always
    volumes:
      - redis-data:/var/lib/redis

volumes:
  abibliadigital:
  mongo-abibliadigital-db-data:
  mongo-abibliadigital-db-log:
