services:
  abibliadigital-app:
    build: ./docker-api
    command: [ "bash", "/usr/src/api/start.sh" ]
    restart: always
    volumes:
      - abibliadigital-redis:/usr/src/api
    depends_on:
      - abibliadigital-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.biblia-api.rule=Host(`biblia-api.vitordaniel.com`)"
      - "traefik.http.routers.biblia-api.entrypoints=websecure"
      - "traefik.http.services.biblia-api.loadbalancer.server.port=300"

  abibliadigital-redis:
    image: "redis:alpine"
    command: redis-server
    restart: always
    volumes:
      - abibliadigital-redis:/var/lib/redis

  abibliadigital-mongodb:
    image: mongo
    volumes:
      - abibliadigital-mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: abibliadigital

volumes:
  abibliadigital-redis:
  abibliadigital-mongodb:
